service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-2

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  fastapiApp:
    name: tuesday-test
    handler: api/main.handler
    description: test-lambda
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
    # layers:
    #   - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: any