service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-2

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true  # docker 환경에서 python package 빌드, site-packges 압축전 사이즈 262mb가 넘으면 안됨
    layer:
      name: test-layer
      description: fastapi test layer
      compatibleRuntimes:
        - python3.8
  warmup:
    default:
      enabled: true # 기본값으로 5분마다 warmup trigger

functions:
  fastapiApp:
    name: tuesday-test
    handler: api/main.handler
    description: test-lambda
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: any